### ISSUE TITLE
Build issues with jacdac extension

### ISSUE THREAD

**Issue by ross-inksmith** [microsoft/jacdac#1246]
Started as a [discussion](https://github.com/microsoft/jacdac/discussions/1241) but moved to issue after messaging Tom.

Normally for testing an extension, in the extension folder I can run `pxt target microbit; pxt build --install` (for the first time, `pxt build` afterwards) to generate a `.hex` to import to makecode, or share internally.

For a new project:
`makecode init microbit jacdac; pxt target microbit; pxt build --install` fails with the following error:
`TS2339: Property 'allocateEventSource' does not exist on type 'typeof control'`, the issue is on [routing.ts:1031](https://github.com/microsoft/pxt-jacdac/blob/a30a0016b78134a137d259e385ccccc77e849ead/routing.ts#L1031)

Building with `mkc build` makes a file that fails to import.

Thanks in advance

**Comment by pelikhan** [comment]
If you are using the 'makecode' tool, you do not need to use `pxt` as they are separate toolchains. You use `mkc build` to create a .hex file, which in fact, does not contain any sources.

In order to test blocs, push your changes to a branch and open this branch in the makecode editor using the github integration.
