### ISSUE TITLE
Losing events

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#19]
In the record page, when devices are streaming, button events are lost.

* connect accelerometer,
* enable collection on fields
* select button event to start/stop
* try click and event are not coming in

**Comment by mmoskal** [comment]
@jamesadevine I think reliable transmission of events is the main outstanding item in the protocol.

IMHO the alternatives are:
* send each event N times (maybe 3); probably requires timestamping events
* support a single pipe from sensor to brain that would carry all events (in addition to broadcasting them)
* complicate the base protocol in some way

Comments?

**Comment by jamesadevine** [comment]
I don't know what the default streaming rate is, but if it is 25 ms, then there should be plenty of bandwidth remaining. I think it's worth trying to understand where the events are going before we take action:

- Are they being lost because the brain's rx packet queue has been exceeded?
- Are they being lost because the sensors' tx packet queue has been exceeded?
- Are they being lost because of a software bug somewhere else in the stack?
- Are they being lost because of simultaneous transmission?

I agree that reliability of events are important, and of the options you listed: 
* option one is the simplest, but I feel its inefficient and inelegant.
* option two is more complex to implement (esp. on small mcus) but some infrastructure already exists.
* option three was presented in a way that assumes the resulting solution would be complex, which may not necessarily true.

**Comment by pelikhan** [comment]
In any case, exposing the QoS services as a register is good info to debug a network.

**Comment by jamesadevine** [comment]
QoS of what? The bus?

**Comment by mmoskal** [comment]
well, the things that were floated put additional real time requirements which is easy on some systems and difficult on others; eg on ESP the reception of the final BRK interrupt may be quite slow (say 100us); the initial one can be also slow, but the UART is configured for reception even before it sees BRK.

there is only so much weirdness budget for the physical layer, and I think we have already used it all with the initial BRK and hard timing constraints

**Comment by pelikhan** [comment]
Yes QoS: number of dropped packets on each queue.

**Comment by jamesadevine** [comment]
@mmoskal do you know where these packets are going?

**Comment by mmoskal** [comment]
No idea

**Comment by pelikhan** [comment]
Should we start by exposing some a QoS register? A register that returns a buffer with state of queue, detected collisions, etc...

**Comment by pelikhan** [comment]
The whole point of ML is to turn a stream of data into events, so events are gold and should not be lost.

**Comment by pelikhan** [comment]
Ideas:
- events have a serial number that "increment" on each event
- have a register with history of event+timestamp+event serial number
- announce packet has the most recent event serial number
- double/triple send each event?

**Comment by tballmsft** [comment]
what about event subscriptions? If I am programming the brain, I probably would want to register for particularly events.

**Comment by tballmsft** [comment]
Send each event N times (maybe 3):
- 16 bits for event identifier,
- 8 bits for counter
- 8 bits reserved
- X bytes for payload (optional)

- additional byte in announce packet with last event id?
