### ISSUE TITLE
Don't add _ to name

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#3]
It's a bit of a weird convention to have the _ in base/sensor. I'd just use the name.

**Comment by mmoskal** [comment]
The base classes have to be processed by the spec tool before regular ones. I do that now with `files.sort()` (with the `_` coming first). Otherwise I will have to explicitly list these classes, or do some topo-sort.

Also the services with underscores should probably not be handled the same was as ones without (eg they have no class identifier).
