### ISSUE TITLE
dealing with noisy values (closeTo implementation)

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#320]
the implementation of closeTo(expr,goal,error) records the goal and error values and continuously evaluates expr until its value is in [goal-error, goal+error]. However, as the expr may bounce around a bit, it's possible that after getting in range, it bounces out, then in, etc. Perhaps we should keep a window of last N readings and when we are in range for more than N/2 of the last N readings, declare success. Thoughts?

**Comment by pelikhan** [comment]
We should have a function to apply a filter (first order, moving average,...) to the data since tuning the filtering is dependent on the sensor

________________________________
From: Tom Ball ***@***.***>
Sent: Thursday, April 1, 2021 2:48:52 AM
To: microsoft/jacdac ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/jacdac] closeTo implementation (#320)


the implementation of closeTo(expr,goal,error) records the goal and error values and continuously evaluates expr until its value is in [goal-error, goal+error]. However, as the expr may bounce around a bit, it's possible that after getting in range, it bounces out, then in, etc. Perhaps we should keep a window of last N readings and when we are in range for more than N/2 of the last N readings, declare success.

**Comment by tballmsft** [comment]
We also need to talk about significant digits with respect to testing. For example, with the potentiometer, the spec says position is u0.16, but we really don't expect to get that sort of accuracy for many devices. So, for example, with the slider what sort of accuracy do we expect (.01, .001)?

**Comment by jamesadevine** [comment]
I know we've had a lot of discussions on buttons recently, but I think it might make sense to employ common de-bouncing techniques instead of anything else. I.e. if > value set flag, check again in x, if > value && flag set -> success

**Comment by tballmsft** [comment]
that's simple and easy to implement.

**Comment by pelikhan** [comment]
With respect to the error, things are a bit more interresting (and we'll probably need a little helper in TS):

for any reading register, there might be an _optional_ reading_error register that provides the current error rate, on top of a default error specified in the spec. So when a compliance test checks that a reading is close to a value, we should be able to use this "current error" value automatically.

**Comment by pelikhan** [comment]
So write something like:
   ``closeTo(angle, 0.5, angle_error)`` 
where ``angle_error`` is the optional reading_error register. If the register does not exist, use default value given in spec (enfore that spec has default values).

**Comment by mmoskal** [comment]
I think typically you would ask user to say move the slider to the middle position - the error on that is much more on the user side, not the sensor side. But I guess say 2*reading_error is probably a good default.
