### ISSUE TITLE
product ID

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac#565]
for example:
* bootloader product ID - mikroe converter board
* product ID - mikroE converter + air quality 4

Tasks
* [x] There is one product ID for each h/w revision. The JSON should keep a list of product IDs.
* [x] The bootloader needs to support different bootloader and non-uploader
* [x] work out the CSV thing
* [x] update the specification - rename firmware ID to product ID

cc @jamesadevine

**Comment by jamesadevine** [comment]
Also, we need a story for Brains...

**Comment by pelikhan** [comment]
@jamesadevine test commisioner. qrcodes should redirect once they are defined in the device catalog

**Comment by jamesadevine** [comment]
awesome! and what's the story with Brains? Do they get a product id? If so, how?

**Comment by pelikhan** [comment]
Yes they should, and the device spec should mention that they are brains. We should discuss brains further

**Comment by mmoskal** [comment]
How would we persist the firmware ID on a brain? Bootloader? Eg an Arcade program would be the same for meowbit and brainpad, so the info would need to come from bootloader I guess? What about micro:bit?

**Comment by jamesadevine** [comment]
As per your point, that would require someone to update the bootloader of their arcade device. IMO it might be more prudent, for the time being at least, to have a product id for `<PROCESSOR>_GENERIC_ARCADE` and allocate a CFG_ID for jacdac product id in the bootloader. From now on, boards that want to support jacdac can add this CFG to their bootloader. Devices with an updated bootloader will get the specific variant stored in the bootloader, while every other board will have the GENERIC_ARCADE product id.

There will likely be a long tail of microcontroller dev boards that will use the edge connector breakout to add Jacdac. We therefore can't rely on bootloaders for everyone of these dev boards...

For micro:bit, do we need to worry about storing the product id in the bootloader? Jacdac only works for binaries that are compiled with the pxt-jacdac extension. Could we have a macro that defines the product id there? 

Because the product id is not stored consistently, it seems like we might need a product id list. That way third party integrators (for say cpy/upy) could implement a product id register in their respective runtime environments.
