### ISSUE TITLE
USB HID Keyboard on RP2040

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#586]
Title!

**Comment by mmoskal** [comment]
It seems this is much more complicated than I thought. It would require patching up the esp-idf, replacing the build system, or somehow bringing in our own copy of TinyUSB. You'll note that this is something Arduino is doing: https://github.com/espressif/arduino-esp32/tree/master/tools/sdk/esp32s2/lib - see `libarduino_tinyusb.a`.

Otherwise, we could fork esp-idf and prep a docker image for building.

**Comment by jamesadevine** [comment]
Feasible for Hackathon? Or do you think it is too much work?

**Comment by jamesadevine** [comment]
Would it be reasonable to depend on the arduino version of the esp-idf?

**Comment by jamesadevine** [comment]
The other thing we could do is build a one off UF2 that acts as a keyboard and mouse Jacdac->HID device for esp32. This would reduce overhead as we wouldn't have to set up all the infrastructure.
