### ISSUE TITLE
rename 'dummy' directory to 'hal'

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#63]
the files in the "dummy" directory of "interfaces" really represent the hardware abstraction layer that JD relies on. Can we use a different name than "dummy"?  Perhaps "hal"?

**Comment by jamesadevine** [comment]
@tballmsft jacdac-c is designed so that developers can pick and choose the part of jacdac-c relevant to them. To resolve compiler errors caused by only partially including jacdac-c, the library provides dummy implementations that have no functionality. Happy to change to a term that sounds better than dummy though :smile:

**Comment by pelikhan** [comment]
Rename it "template" and add TODOs in each funciton that needs to be implemented.

**Comment by pelikhan** [comment]
Or "platform", "hal" is a bit too mysterious for me.

**Comment by mmoskal** [comment]
"hal" is a common term in embedded and systems development
