### ISSUE TITLE
Update jacdac logo

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#669]
Outdated jacdac edge connector svg here:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/4742697/134536664-ab6151b8-20a8-44f3-84bf-8336a7e51e0e.png)

Should look like:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/4742697/134536666-33003ca8-f955-43a9-b8fb-b13c1088d209.png)

**Comment by pelikhan** [comment]
I do not have this logo. Please stop changing it.

**Comment by pelikhan** [comment]
Fixed. Stop changing the logo.

**Comment by mgabrieledamone** [comment]
FYI the logo was changed for the last time in February 2021. Indeed if you have a look at the "Jacdac Manufacturer pitch deck" we made in March, and also the more recent Azure IoT deck, they both have this "new" logo on their first slide. The only change we made since February was turning the logo by 90 degrees to the right (which we decided in a Jacdac stand-up Teams call a few weeks ago).

Anyway, my fault. I'll make sure that all changes in the future will be communicated and updated more clearly. Sorry for the misunderstanding and thanks for updating this logo across the whole website 👍 Looks great!!
