### ISSUE TITLE
Rotary control module resetting

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#686]
Needs to be reprogrammed

**Comment by mmoskal** [comment]
I couldn't see it reset after several minutes on the bus with both 0.14.1 and current 0.17.1 firmware. 

However, it does reset often when another device is connected to the bus. This is due to voltage drop from 4V to 1.8V for about 1-3ms. I think the rotary might be more susceptible to that since it wakes up every 1ms not every 10ms like the other modules. This only happens with the low-power provider (jacdapter). When the bus is powered from RP2040 brain (in addition to m:b) there are some transients but nothing resets.

@jamesadevine @pelikhan does this description fit with your experience?

**Comment by jamesadevine** [comment]
Peli, what product identifier do the logs have for the rotary that was resetting a whole bunch?

James
________________________________
