### ISSUE TITLE
picture of joystick should be rotated

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#753]
The current picture of the joystick should be rotated 90 clockwise so that the x-axis of the silkscreen is pointing to the right and the y-axis is pointing up.

**Comment by pelikhan** [comment]
Can you annotate an image to explain? Is this a silk or simulator issue?
________________________________
From: Tom Ball ***@***.***>
Sent: Sunday, October 3, 2021 5:14:29 PM
To: microsoft/jacdac ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/jacdac] picture of joystick should be rotated (#753)


The current picture of the joystick should be rotated 90 clockwise so that the x-axis of the silkscreen is pointing to the right and the y-axis is pointing up.

**Comment by tballmsft** [comment]
i am talking about the picture associated with the device:  see the silk 

![image](https://user-images.githubusercontent.com/10767146/135795039-7b5a98e3-8e2b-4001-87ed-d26d074b4622.png)

**Comment by pelikhan** [comment]
Picture needs to be retaken then.
