### ISSUE TITLE
Rolemanager is unstable

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#798]
I was building a project with two buttons. I created two button variables. The "assign role" ellipses above the device twin did not appear until I refreshed the browser (even though the program knew there were two button roles and there were two buttons connected to the bus).

**Comment by mmoskal** [comment]
It looks like at least some pipe queries (at least the wifi ones) are sent twice; moreover they are sent with ACKs which is bad, since that causes the server to send the pipe packets twice to the same port. It was also making ESP32 run out of memory

need to figure out these reliable commands and nacks #571 and #564
