### ISSUE TITLE
QoS insights at runtime

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#90]
Provide QoS statistics to end users (e.g. device manufactures, makers) for better identification of bus bottle necks.

**Comment by pelikhan** [comment]
So the idea is stuff the number of packets sent in the announce packet. This allows a listener to:

- [ ] compute how packets were missed from a particular device
- [ ] have a register that exposes QoS stats

Questions:
- [ ] what happens when annouce packets are missed? We should probably also have a counter for this

**Comment by pelikhan** [comment]
I stumbled on this. Is this active code @mmoskal ? We could surface this in a register.

```
    export function diagnostics(): jacdac.JDDiagnostics {
        return new jacdac.JDDiagnostics(jacdac.__physGetDiagnostics());
    }
```
